name: Web App CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Files
        run: |
          ls
          test -f index.html
          test -f style.css
          test -f script.js

      - name: Send Mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}

          subject: Workflow Success
          to: sganeshkvnr@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}

          body: GitHub workflow completed.

      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Auto Pull Request
          body: PR created automatically.
          branch: auto-pr-${{ github.run_number }}
          base: main